In [2]:
### PFDF Documentation : <https://ghsc.code-pages.usgs.gov/lhp/pfdf/api/data/noaa/atlas14.html> ###
!pip install pfdf -i https://code.usgs.gov/api/v4/groups/859/-/packages/pypi/simple

Looking in indexes: https://code.usgs.gov/api/v4/groups/859/-/packages/pypi/simple
Requirement already satisfied: pfdf in /usr/local/lib/python3.12/dist-packages (3.0.4)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from pfdf) (2.4.0)
Requirement already satisfied: fiona in /usr/local/lib/python3.12/dist-packages (from pfdf) (1.10.1)
Requirement already satisfied: numba>=0.57 in /usr/local/lib/python3.12/dist-packages (from pfdf) (0.60.0)
Requirement already satisfied: numpy<2.4 in /usr/local/lib/python3.12/dist-packages (from pfdf) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pfdf) (2.2.2)
Requirement already satisfied: pysheds==0.4 in /usr/local/lib/python3.12/dist-packages (from pfdf) (0.4)
Requirement already satisfied: rasterio in /usr/local/lib/python3.12/dist-packages (from pfdf) (1.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pfdf) (2.32.4)
Requirement already satisfied: shapely in /usr/local/lib/python3.12/dist-packages (from pfdf) (2.1.2)
Requirement already satisfied: geojson in /usr/local/lib/python3.12/dist-packages (from pysheds==0.4->pfdf) (3.2.0)
Requirement already satisfied: looseversion in /usr/local/lib/python3.12/dist-packages (from pysheds==0.4->pfdf) (1.3.0)
Requirement already satisfied: pyproj in /usr/local/lib/python3.12/dist-packages (from pysheds==0.4->pfdf) (3.7.2)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from pysheds==0.4->pfdf) (0.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pysheds==0.4->pfdf) (1.16.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.57->pfdf) (0.43.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio->pfdf) (25.4.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from rasterio->pfdf) (2026.2.25)
Requirement already satisfied: click!=8.2.*,>=4.0 in /usr/local/lib/python3.12/dist-packages (from rasterio->pfdf) (8.3.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio->pfdf) (0.7.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from rasterio->pfdf) (3.3.2)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.12/dist-packages (from fiona->pfdf) (1.1.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pfdf) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pfdf) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pfdf) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pfdf) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pfdf) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pfdf) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pfdf) (1.17.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (3.6.1)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (11.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (2026.3.3)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (26.0)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image->pysheds==0.4->pfdf) (0.5)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

!git config --global user.email "ezuetell@andrew.cmu.edu"
!git config --global user.name "emzu"

try:
    !git clone "https://github.com/emzu/futureIDF"
except:
    print("Already cloned")

%cd /content/futureIDF
!git pull

# Load Packages
!pip install -r requirements.txt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
fatal: destination path 'futureIDF' already exists and is not an empty directory.
/content/futureIDF
Already up to date.
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (2.2.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (1.16.3)
Requirement already satisfied: lmoments3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (1.0.8)
Requirement already satisfied: xarray>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (2026.2.0)
Requirement already satisfied: geopandas>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (1.1.3)
Requirement already satisfied: rasterio>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (1.5.0)
Requirement already satisfied: rioxarray>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (0.22.0)
Requirement already satisfied: regionmask>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 12)) (0.13.0)
Requirement already satisfied: shapely>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 13)) (2.1.2)
Requirement already satisfied: matplotlib>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 16)) (3.10.0)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 17)) (0.13.2)
Requirement already satisfied: cartopy>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 18)) (0.25.0)
Requirement already satisfied: dask>=2021.10.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2026.1.2)
Requirement already satisfied: jupyterlab>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 24)) (4.5.6)
Requirement already satisfied: ipykernel>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 25)) (6.17.1)
Requirement already satisfied: zarr>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 26)) (3.1.6)
Requirement already satisfied: netcdf4>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 27)) (1.7.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 28)) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->-r requirements.txt (line 3)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->-r requirements.txt (line 3)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->-r requirements.txt (line 3)) (2025.3)
Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.12/dist-packages (from xarray>=0.19.0->-r requirements.txt (line 8)) (26.0)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.10.0->-r requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.10.0->-r requirements.txt (line 9)) (3.7.2)
Requirement already satisfied: affine in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (2.4.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (25.4.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (2026.2.25)
Requirement already satisfied: click!=8.2.*,>=4.0 in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (8.3.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (0.7.2)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from rasterio>=1.2.0->-r requirements.txt (line 10)) (3.3.2)
Requirement already satisfied: pooch>=1.7 in /usr/local/lib/python3.12/dist-packages (from regionmask>=0.9.0->-r requirements.txt (line 12)) (1.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->-r requirements.txt (line 16)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->-r requirements.txt (line 16)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->-r requirements.txt (line 16)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->-r requirements.txt (line 16)) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.0->-r requirements.txt (line 16)) (11.3.0)
Requirement already satisfied: pyshp>=2.3 in /usr/local/lib/python3.12/dist-packages (from cartopy>=0.20.0->-r requirements.txt (line 18)) (3.0.3)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2025.3.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (0.12.1)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (3.1.6)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.14.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (75.2.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (6.5.1)
Requirement already satisfied: traitlets in /usr/local/lib/python3.12/dist-packages (from jupyterlab>=3.0.0->-r requirements.txt (line 24)) (5.7.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=6.0.0->-r requirements.txt (line 25)) (26.2.1)
Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.12/dist-packages (from zarr>=2.10.0->-r requirements.txt (line 26)) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr>=2.10.0->-r requirements.txt (line 26)) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.12/dist-packages (from zarr>=2.10.0->-r requirements.txt (line 26)) (0.16.5)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from zarr>=2.10.0->-r requirements.txt (line 26)) (4.15.0)
Requirement already satisfied: cftime in /usr/local/lib/python3.12/dist-packages (from netcdf4>=1.5.0->-r requirements.txt (line 27)) (1.6.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 28)) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 28)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->-r requirements.txt (line 28)) (2.5.0)
Requirement already satisfied: pyarrow>=16.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (18.1.0)
Requirement already satisfied: lz4>=4.3.2 in /usr/local/lib/python3.12/dist-packages (from dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (4.4.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.16.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.0.3->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (3.0.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (4.9.4)
Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (25.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (7.17.0)
Requirement already satisfied: nbformat>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.24.1)
Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (1.9.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.14.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (4.26.0)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->-r requirements.txt (line 3)) (1.17.0)
Requirement already satisfied: distributed<2026.1.3,>=2026.1.2 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2026.1.2)
Requirement already satisfied: bokeh>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (3.8.2)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (25.1.0)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2.18.0)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2025.11.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (1.1.2)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (3.2.2)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask>=2021.10.0->dask[complete]>=2021.10.0->-r requirements.txt (line 21)) (3.0.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.0.0->-r requirements.txt (line 25)) (0.8.6)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.30.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (4.0.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.1.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab>=3.0.0->-r requirements.txt (line 24)) (0.3.0)

In [4]:
import os
import geopandas as gpd
import pandas as pd
import pfdf
from pfdf.data.noaa import atlas14
import time

In [7]:
!git pull

# Import modules
import sys
import importlib
# Ensure workspace root is on sys.path so the local `modules` package can be imported
sys.path.append('..')

import numpy as np
import matplotlib.pyplot as plt
import xarray as xr
import glob
import os
import warnings
warnings.filterwarnings('ignore')

from modules import config, data_io, timeseries, plotting, process_rp, geospatial
importlib.reload(timeseries)
importlib.reload(data_io)
importlib.reload(process_rp)
importlib.reload(geospatial)

remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (9/9), 9.78 MiB | 6.54 MiB/s, done.
From https://github.com/emzu/futureIDF
   113e3b7..f59568f  main       -> origin/main
Updating 113e3b7..f59568f
Fast-forward
 data/Boundaries/MARISA_domain.cpg |   1 +
 data/Boundaries/MARISA_domain.dbf | Bin 0 -> 42280 bytes
 data/Boundaries/MARISA_domain.prj |   1 +
 data/Boundaries/MARISA_domain.shp | Bin 0 -> 14124060 bytes
 data/Boundaries/MARISA_domain.shx | Bin 0 -> 2196 bytes
 5 files changed, 2 insertions(+)
 create mode 100644 data/Boundaries/MARISA_domain.cpg
 create mode 100644 data/Boundaries/MARISA_domain.dbf
 create mode 100644 data/Boundaries/MARISA_domain.prj
 create mode 100644 data/Boundaries/MARISA_domain.shp
 create mode 100644 data/Boundaries/MARISA_domain.shx

In [8]:
counties_gdf = data_io.load_counties()
# Create lists to store results
results = []

In [33]:
# Create output directory
out_dir = 'content/atlas14_data'
os.makedirs(out_dir, exist_ok=True)

# Store 24-hr data for all counties
county_24hr_data = pd.DataFrame()

# Download for each county
for idx, county in counties_gdf[:1].iterrows():
    try:
        centroid = county.geometry.centroid
        lon, lat = centroid.x, centroid.y

        county_name = county.get('NAME')
        state_name = county.get('STATE')

        csv_path = atlas14.download(
            lat=lat,
            lon=lon,
            series='pds',
            statistic='all',
            data='intensity',
            units='english',
            parent='content/atlas14_data',
            name=f"{county_name}_{state_name}_{idx}.csv",
            overwrite=False
        )

        # Read the CSV
        df = pd.read_csv(csv_path, header = 11)
        df.set_index('by duration for ARI (years):', inplace=True)

        data_24hr = df.loc['24-hr:']
        # Add county info
        data_24hr = data_24hr.copy()*24
        data_24hr['county_name'] = county_name
        data_24hr['county_fips'] = county.get('FIPS', None)
        data_24hr['lon'] = lon
        data_24hr['lat'] = lat
        data_24hr['idx_ref'] = idx
        data_24hr.index = pd.Index(['mean', 'upper', 'lower'], name='CI')

        county_24hr_data = pd.concat([county_24hr_data, data_24hr], axis=1)

        print(f"Downloaded {county_name}: extracted {len(data_24hr)} 24-hr records")
        time.sleep(1)

    except Exception as e:
        print(f"Error for county {county.get('NAME', idx)}: {e}")
        continue

# Combine all 24-hr data
all_24hr = county_24hr_data.set_index('county_name')
print(f"\nTotal 24-hr records: {len(all_24hr)}")

Downloaded Beaver: extracted 3 24-hr records

Total 24-hr records: 3

In [34]:
county_24hr_data

,1,2,5,10,25,50,100,200,500,1000,county_name,county_fips,lon,lat
CI,,,,,,,,,,,,,,
mean,1.968,2.352,2.880,3.288,3.912,4.392,4.920,5.448,6.216,6.816,Beaver,None,-80.349295,40.682262
upper,2.112,2.520,3.096,3.552,4.176,4.704,5.232,5.808,6.600,7.224,Beaver,None,-80.349295,40.682262
lower,1.848,2.184,2.688,3.072,3.624,4.056,4.512,4.992,5.664,6.168,Beaver,None,-80.349295,40.682262

In [ ]:
all_24hr.reset_index(inplace=True)
all_24hr.rename(columns={'index': 'county_name'}, inplace=True)

In [ ]:
all_24hr

,county_name,1,2,5,10,25,50,100,200,500,1000,county_fips,lon,lat
0,Beaver,1.968,2.352,2.88,3.288,3.912,4.392,4.92,5.448,6.216,6.816,None,-80.349295,40.682262
1,Salem,2.496,3.024,3.84,4.512,5.472,6.288,7.176,8.136,9.504,10.656,None,-80.055475,37.286403
2,Montgomery,2.28,2.784,3.528,4.152,5.04,5.784,6.6,7.464,8.736,9.768,None,-80.387215,37.174291
3,Poquoson,2.904,3.552,4.584,5.496,6.84,7.992,9.288,10.752,12.936,14.832,None,-76.2705,37.150278
4,James City,2.928,3.552,4.584,5.472,6.792,7.92,9.168,10.584,12.672,14.448,None,-76.773867,37.313338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Ontario,1.92,2.28,2.856,3.336,3.984,4.464,5.016,5.664,6.72,7.608,None,-77.481723,42.588807
258,Madison,2.04,2.424,3.072,3.6,4.32,4.848,5.424,6.096,7.056,7.872,None,-75.57269,42.812959
259,Onondaga,2.04,2.424,3.072,3.6,4.32,4.872,5.424,6.072,7.008,7.752,None,-76.025977,42.822561
260,Oneida,2.112,2.496,3.12,3.624,4.32,4.848,5.4,6.048,6.96,7.728,None,-75.309267,42.901726
261,Herkimer,2.112,2.472,3.096,3.6,4.272,4.8,5.352,5.976,6.888,7.656,None,-75.043999,42.901474

In [ ]:
all_24hr.to_parquet('atlas14_24hr_data.parquet', index=False)